### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by phildionne**
Here's a massive update regarding the structure of this project.

Basically, it gives two options:
1. Any ruby code, wether it's a gem, sinatra, etc.
2. A rails application

It assumes:
- All ruby & rails projects use rspec
- All documentation is written in Markdown

The goal is for any dev on the team to start from our default configuration and extend as few cops as possible. We should therefore strive to enforce really good defaults.

Inspiration:
- https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
- https://github.com/palkan/action_policy/blob/master/.rubocop.yml

Decisions:
- Ruby: https://github.com/testdouble/standard
- Performance: default https://github.com/rubocop-hq/rubocop-performance
- Rspec: default https://github.com/rubocop-hq/rubocop-rspec
- Rails: https://github.com/rubocop-hq/rubocop-rails combined with https://gist.github.com/palkan/24869b835c45e89116b9727b534e579e

Suggestions:
- Defaults: https://shopify.github.io/ruby-style-guide/
- Defaults: https://github.com/thoughtbot/guides/tree/master/style/ruby
- Rspec: https://gist.github.com/palkan/623c0816b05ed246bfe0cb406050990a

### CODE REVIEW

**Comment by phildionne** [comment]
You may want to take a look at how this configuration works with one of our existing project, check out https://github.com/phildionne/schema-replicator/pull/5

**Comment by phildionne** [comment]
Also consider taking inspiration from https://relaxed.ruby.style/

> A more liberal style guide for RuboCop. It comes with a config file which deactivates some of RuboCop's features. It is meant as a less restrictive foundation that you can use directly or base your style discussions on.

**Review by bricesanchez — COMMENTED** [review]
First of all, i really like the fact we will enforced the code style. That's a great move for every developper!

I've read your links in the PR and i agree of most content.
I've seen what it does in the schema-replicator gem and it looks good for the most of changes,

What i think is missing is :
https://github.com/phildionne/schema-replicator/pull/5/files#diff-6eb6867cce589479023a60bd4f2bce10R56-R58

```
I'm not sure of this rule to strip spaces around { and before }.

I prefer this rules:
Use spaces around operators, after commas, colons and semicolons, around { and before }.
https://github.com/Shopify/ruby-style-guide#formatting

Usage of trailing comma in multi-line collection literals is encouraged. It makes diffs smaller and more meaningful.
https://github.com/Shopify/ruby-style-guide#collections
```
We also have these rules in ESlint. Perhaps, we could standarize some rules between Ruby and JS.

**Comment by phildionne** [comment]
> Use spaces around operators, after commas, colons and semicolons, around { and before }.
> https://github.com/Shopify/ruby-style-guide#formatting

Agreed

> Usage of trailing comma in multi-line collection literals is encouraged. It makes diffs smaller and more meaningful.
> https://github.com/Shopify/ruby-style-guide#collections

Agreed

**Pull request merged**
